version: '3'

volumes:
  postgres-data:
  composer-vendor:

services:
  postgres:
    image: postgres:9.6-alpine
    restart: always
    env_file:
      - ./.devcontainer/services/postgres/env/postgres.env
    ports:
      - '${POSTGRES_HOST_PORT:-5432}:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./.devcontainer/services/postgres/init:/docker-entrypoint-initdb.d
  web-app:
    build:
      context: ./.devcontainer/dockerfiles/web-app
      args:
        TZ: 'Asia/Tokyo'
        COMPOSER_VERSION: 1
    restart: always
    env_file:
      - ./.devcontainer/services/web-app/env/web-app.env
    volumes:
      - ./.devcontainer/services/web-app/conf/php.ini:/etc/php7/php.ini
      - ./.devcontainer/services/web-app/conf/httpd.conf:/etc/apache2/httpd.conf
      - ./.devcontainer/services/web-app/htdocs:/var/www/localhost/htdocs
      - ./.devcontainer/services/web-app/log/apache2:/var/log/apache2
      - ./src:/usr/src
      # Laravel プロジェクトが src 直下でない場合、vendor ディレクトリのパスを調整する
      - composer-vendor:/usr/src/vendor
    ports:
      - '${APACHE_HOST_PORT:-80}:80'
      - '${ARTISAN_SERVE_HOST_PORT:-8000}:8000'
    links:
      - postgres
